### ISSUE TITLE
How can I get the values of SUPPORT_ENDPOINT = "", SUPPORT_KEY = "", and CHAT_ENDPOINT = "", CHAT_KEY = ""?

### ISSUE THREAD

**Issue by dobahoang** [Azure-Samples/contoso-chat#102]
I came across some variables defined in the readme file, but I am unable to find them in the Azure portal. I have made several attempts to locate them but to no avail. Can you please suggest a way to help me out? The variables I'm looking for are SUPPORT_ENDPOINT, SUPPORT_KEY, CHAT_ENDPOINT, and CHAT_KEY which are mentioned in the .env file.

![image](https://github.com/Azure-Samples/contoso-chat/assets/71694838/d10e84f8-3ca3-4141-9be8-4e35d5054919)

please help me !

**Comment by nitya** [comment]
> [!NOTE]  
> This sample is currently undergoing a refresh in preparation for #MSBuild so many of these issues may no longer be relevant. We are closing issues now in preparation for the new version. Check back May 21, 2024 for updated release before posting new issues.
