### ISSUE TITLE
Endpoint test fails due to missing API key

### ISSUE THREAD

**Issue by phoevos** [Azure-Samples/contoso-chat#132]
After completing deployment I can see the endpoint on AI Studio. Following the instructions in the README I proceed to test it with the following input:
```
{"question": "Tell me about hiking shoes", "customerId": "2", "chat_history": []}
```

The above produces an error, however, triggered during the instantiation of the `AzureOpenAIModelConfiguration` object. As seen in the logs:
 
```
"Execution failure in 'get_response': (InvalidConnectionError) AzureOpenAIModel parameters are incomplete. Please ensure azure_endpoint, api_version, and api_key are provided."
 ```

Although we do explicitly provide the version and endpoint [here](https://github.com/Azure-Samples/contoso-chat/blob/3307a05c560d695dd373edd5afbeb8ec5dae1d25/contoso_chat/chat_request.py#L67-L72), we don't do the same for the API key. In fact, inspecting my local `azd env`, the value of `AZURE_OPENAI_API_KEY` is not set. This feels like something that should be part of the postprovision script. Diving deeper, I noticed that a relevant looking key (is it the same one?) used to be set among others [here](https://github.com/Azure-Samples/contoso-chat/blob/f9b0ea994a89731bcb19686c816e1178eca4c80b/infra/hooks/postprovision.sh#L66-L74) prior to the May 2024 updates. Why was this dropped?

I'm currently using the following package versions:
```
prompt_toolkit==3.0.45
promptflow==1.10.0
promptflow-azure==1.10.0
promptflow-core==1.10.0
promptflow-devkit==1.10.0
promptflow-evals==0.3.0
promptflow-tools==1.4.0
promptflow-tracing==1.10.0
```

**Comment by cassiebreviu** [comment]
There is an issue with a dup aoai connection. If you look at the logs it does succeed but something change with AI Studio causing a second failed request. We are testing a fix now and will likely merge it today. As a workaround you can delete the existing default dup aoai connection.

**Comment by cassiebreviu** [comment]
this should be fixed now.
