### ISSUE TITLE
azd up: Failed deployment of Failure-Anomalies-Alert-Rule-Deployment-xxx

### ISSUE THREAD

**Issue by revodavid** [Azure-Samples/contoso-chat#150]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
Launch CodeSpaces
Log into a personal Azure subscription with azd auth
azd up

### Any log messages given by the failure
Failure reported for Deployment Failure-Anomalies-Alert-Rule-Deployment-95c29a3f in Azure Portal:

The subscription is not registered to use namespace 'Microsoft.AlertsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code: MissingSubscriptionRegistration)

### Expected/desired behavior
No deployment failures

### Mention any other details that might be useful
Doesn't seem to cause any actual problems.

**Comment by shresthasource** [comment]
It does not appear to be solved, but manual redeploy from Azure Portal seems to succeed.
