### ISSUE TITLE
Bug in `create-azure-search.ipynb` building the endpoint

### ISSUE THREAD

**Issue by anderl80** [Azure-Samples/contoso-chat#17]
The ´.env´ file suggests to only give the name of the created AI Search service - which is also needed by other code parts. Then, building the endpoint URL in the mentioned notebook fails. Suggest to change cell 3 in this notebook to (like it is already done in the other cells):

```python
def delete_index(search_service: str, search_index: str, search_api_key: str):
    print(f"Deleting index {search_index} in {search_service}...")
    response = requests.delete(
        f"https://{search_service}.search.windows.net/indexes/{search_index}",
        headers={"api-key": search_api_key},
    )
    print(response.status_code)
    return response.status_code
```

**Comment by cassiebreviu** [comment]
Fixed to indicate to add endpoint not name: https://github.com/Azure-Samples/contoso-chat/pull/18

Thanks!

**Comment by sethjuarez** [comment]
Good catch! I made a fix to standardize on a full endpoint given I updated the code to use the GA SDK. @cassiebreviu will review and merge if she's good with the changes.
