### ISSUE TITLE
It will be great if the manual is shared in the repo

### ISSUE THREAD

**Issue by tbandopa** [Azure-Samples/contoso-chat#42]
Though the readme is quite good, it would be great if the manual can be shared.

**Comment by nickcoast** [comment]
You mean the instructions from the presentation? I copy-pasted them into a document. I can share as PDF, docx, or whatever, if you want.

Also check this out, it's similar: https://learn.microsoft.com/en-us/azure/ai-studio/tutorials/deploy-copilot-ai-studio

**Comment by NetWright** [comment]
Hi Nick @nickcoast, the linked tutorial is helpful, thanks! If you get the chance can you also share a docx on the instructions specific to the workshop from San Francisco? Thanks for helping us get up to speed with these resources! Looking forward to setting up some internal AI workspaces so our company can begin developing useful flows.

**Comment by nickcoast** [comment]
HI @NetWright, here you go:

[Microsoft_Azure_production_RAG_tutorial.docx](https://github.com/Azure-Samples/contoso-chat/files/13968758/Microsoft_Azure_production_RAG_tutorial.docx)

Hopefully the formatting isn't too terrible. Other than the title and a couple links I added at the top, it's just what I copy-pasted from the presentation in San Francisco.

**Comment by cassiebreviu** [comment]
We are working on getting the instructions from the workshop added to the repo here. I will update once the PR has been merged. Thanks!!
