### ISSUE TITLE
Models gpt-3.5-turbo, gpt-4, and text-embedding-ada-002 not available?

### ISSUE THREAD

**Issue by nickcoast** [Azure-Samples/contoso-chat#43]
I saw them yesterday, I'm sure. But now I don't see them. I don't know if it's an issue with the Sweden Central region or something else.
![image](https://github.com/Azure-Samples/contoso-chat/assets/15386328/53d79e56-b332-4c99-a387-4509f19e2e0b)

EDIT: After getting no hint of the problem anywhere else, I decided, like a cornered wild animal, to frantically click on every button I could find on ai.azure.com. I came across the "Explore" tab, where I found the "Model Catalog". There, I searched for gpt-35-turbo and found this:

![Screenshot 2024-01-12 at 9 53 15 PM](https://github.com/Azure-Samples/contoso-chat/assets/15386328/bd9150aa-521e-47a8-9e1b-06dc2191ee76)

I shall now continue clicking haphazardly until I can figure out whether its my subscription, or the region, that is preventing me from using this resource. Unless anyone has any tips. Thanks!

**Comment by nitya** [comment]
Are you doing this in your own subscription or are you doing this in an instructor-led session (e.g., with Skillable)?

There are 2 possible reasons for this assuming you have access to Azure Open AI already.
 1. You are in a region that does not have that model available
 2. You are in a region that does have the model available - but you ran out of quota

Try going to https://ai.azure.com
Log in with your subscription then click the **Manage** tab
Note that there is a tab called Quota (screenshot below)
If you pick your subscription. - you can then check if you have quota in a particular region (and it should also list the models available in a specific region).

![image](https://github.com/Azure-Samples/contoso-chat/assets/279083/dffadaa9-70e5-4fa3-bee1-fb22a077ca76)

**If you do have quota in that region, but don't see the models to deploy** then the other issue might be that your Azure AI resource is not connected to an Azure AI Services provider. But that is a different problem and you should not be seeing it if you went through a manual deployment of all resources.

**Comment by nickcoast** [comment]
Thanks! I was able to get it working. I had to fill out a long application form and wait for approval, which was pretty quick.

Azure has some other problems that made it hard to complete the tutorial, but I was able to do it eventually. Looking forward to experimenting with it.

**Comment by nitya** [comment]
Please do share any feedback on issues you saw (so we can add it to a Troubleshooting section for others as well). Glad to hear and look forward to more feedback. 

@cassiebreviu - I think we can close this issue.
