### ISSUE TITLE
Error in connection type

### ISSUE THREAD

**Issue by jvargh** [Azure-Samples/contoso-chat#45]
Get this error when running evaluate-chat-prompt-flow.ipynb, which points to the connection definition in AI Studio. Could a sample be provided to compare? 

```
...
Reason: NotSupported ConnectionType 0 for connection contoso-cosmos. 
Error message: (UserError) NotSupported ConnectionType 0 for connection contoso-cosmos.
Code: UserError
```

**Comment by cassiebreviu** [comment]
The contoso-cosmos custom connection should look like this:
<img width="337" alt="image" src="https://github.com/Azure-Samples/contoso-chat/assets/46505951/6eac90b8-1cad-422a-b6c1-f3cbc94083c4">

**Comment by jvargh** [comment]
Had it recreated but error remains. Below shows local and studio formats. Thoughts?

![image](https://github.com/Azure-Samples/contoso-chat/assets/3197295/13c95385-eba7-4002-827e-659d57cead04)

**Comment by nitya** [comment]
Looking at the output of your screenshot, you need to have 4 key-value pairs and the first one should be called "key". In the list above, I see "key1" in the config but no "key"

**Comment by jvargh** [comment]
it should be taking 'key' from secrets. Running create-connections notebook it did create the below. Will not allow using name 'key' in configs. Error from above remains. Let know if you see the same 
![image](https://github.com/Azure-Samples/contoso-chat/assets/3197295/b4916276-df4d-4dd3-8db0-b2889ac7fbcb)

**Comment by jvargh** [comment]
PG are working on fixing it. For a workaround create the connection in ML studio in promptflow >connections.
