### ISSUE TITLE
Error during deployment

### ISSUE THREAD

**Issue by jvargh** [Azure-Samples/contoso-chat#46]
Get the below error when using push_and_deploy_pf.ipynb to deploy on the 'pf_azure_client.flows.create_or_update' step. Also notice the logs message is truncated so don't see full extent of what happened. Thoughts?

```
ResourceNotFoundError: (UserError) Please make sure that you are passing valid secret names and that the keyvault https://ainorthcentus/
Code: UserError
Message: Please make sure that you are passing valid secret names and that the keyvault https://ainorthcentus/
```

**Comment by nitya** [comment]
My guess is that this is related to #45 - in the step that you identify, the code is looking up the prompt-flow and pushing up that flow (with state) to the cloud. Which means it probably checks that the connections associated with it are valid.

The only secrets that go into the local keyvault are the connection keys (if I recall correctly). And the cosmos key1 "value" (in your other issue) was not valid. It was a string ("test"?) and should have been a complex integer key value.

**Comment by jvargh** [comment]
created a new project/new region and deployment now worked. Not sure resolution of earlier error
