### ISSUE TITLE
Error `Environment '{}' is not registered` when deploying Prompt Flow in Azure AI Studio and ML Studio

### ISSUE THREAD

**Issue by nickcoast** [Azure-Samples/contoso-chat#51]
I tried deploying to 1 instance and to 3 and get the same error every time. Also tried selecting a different instance types. Also tried deploying in ML Studio instead of AI Studio.

`Environment promptflow_a80*************************ab is not registered`

There's a link in the log pointing [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-environments?view=azureml-api-2#no-definition-exists-for-environment). 

But I haven't figured out how to "register" the environment.
I can see the environment it refers to in ML Studio -> contoso-chat-aiproj -> Environments. It says "build failed". If I click the "Rebuild" button there, it rebuilds without error. But when I try to deploy the Prompt Flow, I always get the same error.

Here's the error message from ml.azure.com (I redacted part of my environment name in the two spots its shown):

```
Execution failed. User process 'python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error: Traceback (most recent call last):
  File "prepare.py", line 26, in <module>
    build_local_environment(args.name, args.version, args.platform)
  File "prepare.py", line 15, in build_local_environment
    environment.build_local(workspace, platform, useDocker=True, pushImageToWorkspaceAcr=True)
  File "/azureml-envs/image-build/lib/python3.8/site-packages/azureml/core/environment.py", line 1549, in build_local
    raise UserErrorException("Environment '{}' is not registered".format(self.name))
azureml.exceptions._azureml_exception.UserErrorException: UserErrorException:
	Message: Environment 'promptflow_a80*************************ab' is not registered
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Environment 'promptflow_a80*************************ab' is not registered"
    }
}
```

Also these two warnings (redacted by Azure, not me):

```
AzureMLCompute job failed
ExecutionFailed: [REDACTED]
	exit_codes: 1
	Appinsights Reachable: Some(true)
```
`
Serverless job failed.
`

Here's what I see in the ML Studio notifications:
![image](https://github.com/Azure-Samples/contoso-chat/assets/15386328/0913075f-bf6c-41c2-b595-6da12b2e2706)

Also, I've been assuming that when I deploy the Prompt Flow, I do *not* have to use 3 instances? I've tried with 1 and with 3 and I get the same error with the same exact "not registered" environment in both cases.

Thank you!

**Comment by cassiebreviu** [comment]
Hey! This is a bug we are aware of and are working on. Should be fixed soon. I will update here once the fix is deployed.

**Comment by nickcoast** [comment]
Great!
Just curious - does this mean it's been impossible to complete this tutorial up until now?
Or is it an idiosyncratic bug that might go away if I redo some of the steps?

**Comment by cassiebreviu** [comment]
No, it was a bug that was recently introduced.

**Comment by nickcoast** [comment]
Is it a bug in this repo, or in Azure?
