### ISSUE TITLE
The README is missing the step to create a custom connection for Cosmos DB

### ISSUE THREAD

**Issue by gloveboxes** [Azure-Samples/contoso-chat#52]
Required to successfully run evaluate-chat-prompt-flow.ipynb

Creating Custom Connection (contoso-cosmos)

1. Visit https://ml.azure.com instead
1. Under Recent Workspaces, click project (contoso-chat-aiproj)
1. Select Prompt flow (sidebar), then Connections (tab)
1. Click Create and select Custom from dropdown
1. Name: contoso-cosmos
1. Provider: Custom (default)
1. Key-value pairs: Add 4 entries (get env var values from .env)
1. key: key, value: "COSMOS_KEY", check "is secret"
    1. key: endpoint, value: "COSMOS_ENDPOINT"
    1. key: containerId, value: customers
    1. key: databaseId, value: contoso-outdoor
    1. Click Save to complete step.

**Comment by revodavid** [comment]
This issue appears to be resolved now (see Step 4.6 in README.md)
