### ISSUE TITLE
No Kernel Available When Trying To Select Kernel in GitHub Codespaces VS Code Editor

### ISSUE THREAD

**Issue by mashhype** [Azure-Samples/contoso-chat#58]
Hello,

I'm on this step: https://nitya.github.io/contoso-chat/02%20%7C%20Workshop/05%20%7C%20Setup%20Promptflow/11-populate-index/ and when I click on "Select Kernel" in the top right hand corner icon, nothing happens. Theres no Kernel available. Is there a way to fix this or some kind of workaround?

**Comment by revodavid** [comment]
I had a similar issue when the codespace stopped automatically. I was able to work around it by deleting and relaunching the codespace (be sure to sync your .env and config.json files).
