### ISSUE TITLE
Cell 12 in Step 18 notebook "evaluate-chat-prompt-flow.ipynb" returns "InteractiveBrowserCredential.get_token failed: Timed out after waiting 300 seconds for the user to authenticate" error after 5 minutes of running

### ISSUE THREAD

**Issue by mashhype** [Azure-Samples/contoso-chat#61]
I authenticated using `az login --use-device-code` in the previous cell successfully...
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/c3d902e5-2b65-484d-833a-7c05edfefe23)

**Comment by mashhype** [comment]
I restarted my codespace and reran the notebook. Now on cell 12, I get the following error:
"UserErrorException: (AuthorizationFailed) The client 'xxx@microsoft.com' with object id 'xxx' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/xxx/resourceGroups/rg-mashsyedai/providers/Microsoft.MachineLearningServices/workspaces/contoso-chat-aiproj' or the scope is invalid. If access was recently granted, please refresh your credentials."

I updated the projects access by adding read permissions the machine learning workspace using Managed Identity...still got the same error above

**Comment by cassiebreviu** [comment]
Can you get lastest and try again? We made some updates to the code yesterday.

**Comment by mashhype** [comment]
Synced to the original repo and now I get this error when running cell 12:
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/06207497-5f37-4aa5-bc37-9c08532c378d)

**Comment by cassiebreviu** [comment]
login with az login and also check the props in config.json to make sure they are correct.

**Comment by mashhype** [comment]
Ok did ` az login --use-device-code` and successfully logged in. Also double checked my config.json file and it matches what I have in the portal...
Then ran cell 12 and got this error:
"UserErrorException: (AuthorizationFailed) The client 'mashsyed@microsoft.com' with object id '57548c14-d0f2-4172-94cf-6d1aaa8c395f' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/1d6691ec-2e1f-4547-9f76-c944326eaf49/resourceGroups/rg-mashsyedai/providers/Microsoft.MachineLearningServices/workspaces/contoso-chat-aiproj' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client 'xxx@microsoft.com' with object id 'xxx' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/xxx/resourceGroups/rg-mashsyedai/providers/Microsoft.MachineLearningServices/workspaces/contoso-chat-aiproj' or the scope is invalid. If access was recently granted, please refresh your credentials."

_Note, I have my personal GitHub linked to my Microsoft employee GitHub acct as I am testing this repo in order to prepare for customer workshops where I will deliver this to multiple customers...._

**Comment by cassiebreviu** [comment]
Did you create the project? Can you check the settings and permissions on the project? Can you make sure the config has the project name as the workspace hub name?

**Comment by mashhype** [comment]
I just re-ran the notebook and this time, on cell 11, it tells me that DefaultAzureCredential failed and that Interactive authentication is needed and to run `az login --scope https://management.azure.com/.default`

When I do that, I this new tab open up:
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/49aefcee-177f-4dee-8139-230ce423ee89)

**Comment by mashhype** [comment]
Not sure what else I am supposed to add here, Im already listed as the owner of the resources:
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/0c3b5689-899c-4e35-a320-b975bd2aeb71)

**Comment by cassiebreviu** [comment]
Without actually looking at your code the error that you posted looks like the workspace_name name is the resource name and not the project name. Are you still getting the same auth error or is it different now?

**Comment by mashhype** [comment]
Hi @cassiebreviu heres a screen shot of my workspace and rg from AML, it shows the workspace name is my project name....
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/e20ca759-b6d7-431b-92d9-ab55941d8802)

**Comment by cassiebreviu** [comment]
Ended up being subscription issue. Closing request.
