### ISSUE TITLE
How to fetch more relevant products based on the previous question

### ISSUE THREAD

**Issue by coderSinol** [Azure-Samples/contoso-chat#65]
It looks like the prompt flow cannot fetch products based on the chat history. For instance, if I asked for rain jackets, it would suggest a few. But if I ask "Can you suggest more?", then it provides random products without considering the chat history.

**Comment by cassiebreviu** [comment]
How are you running the promptflow? Are you setting the chat history prop when you call it?

**Comment by coderSinol** [comment]
Thank you for your reply. I found the issue. My JSON data structure had an issue.

This is how I configured chat history in the customer prompt. Is that correct?

# History
{% for item in chat_history %}
user: 
{{item.inputs.question}}:
assistant: 
{{item.outputs.answer}}
{% endfor %}
