### ISSUE TITLE
flow.dag.yaml Visual Editor Cannot Find question_embedding tool

### ISSUE THREAD

**Issue by mashhype** [Azure-Samples/contoso-chat#67]
I'm running this locally in VS Code using a venv. When I try to run the flow through the visual editor, it fails with `AttributeError: 'EntryPoints' object has no attribute 'get'`

In the visual editor, I see that the question_embedding node shows an error: "Can't find tool promptflow.tools.embedding.embedding
The package may not be installed in your Python environment."

I can see an embeddings.py file in my venv folder:
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/e8b7fcc8-68e7-47e1-92a3-36fbf84f61ae)

Here's a screen shot of the error in the PF visual editor in VS Code
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/661b5a1e-9d05-43db-9372-aa9a862c2e5b)

**Comment by cassiebreviu** [comment]
You are missing the promptflow-tools package. Please pip install the requirements file which includes the necessary packages.
