### ISSUE TITLE
Unable to launch solution in Github Codespaces

### ISSUE THREAD

**Issue by TheeUnderdog** [Azure-Samples/contoso-chat#68]
After I create the codespace, I am being presented with an authorizatin dialog over and over again.

![image](https://github.com/Azure-Samples/contoso-chat/assets/73850129/ec1bc24b-d5a1-4841-9fa6-4ac7761325c5)

![image](https://github.com/Azure-Samples/contoso-chat/assets/73850129/f61ca0bd-667d-4d4c-b9f8-a86b0e83d133)

**Comment by cassiebreviu** [comment]
This looks like a codespaces issue with an extension auth issue. Did you try removing the extension that is popping up? You can always run locally and not use codespaces as well.
