### ISSUE TITLE
Connection contoso-cosmos not found

### ISSUE THREAD

**Issue by DiegoZumarragaLS** [Azure-Samples/contoso-chat#70]
Hi
I am trying to deploy the prompt flow to Azure AI Studio but when I run a test it indicates that the contoso-cosmos connection was not found, even though the connection is created, I attach the screen shots. Any idea how it can be solved?

![Captura de pantalla prompt flow](https://github.com/Azure-Samples/contoso-chat/assets/140433136/7f59fd07-51ff-4012-bea6-5a6a7086c9ae)

![Captura de pantalla Conexion cosmos](https://github.com/Azure-Samples/contoso-chat/assets/140433136/1ea0c5a9-d0ea-46af-93e5-59a481af8c9b)

**Comment by cloga** [comment]
Please follow this part to add extra meta to use custom connection in promptflow: https://learn.microsoft.com/en-us/azure/ai-studio/how-to/prompt-flow-tools/python-tool#create-a-custom-connection
