### ISSUE TITLE
OpenAI API hits NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### ISSUE THREAD

**Issue by julianurregoar** [Azure-Samples/contoso-chat#76]
Hello Azure team,

Thanks for this good repo!

I am facing a small issue during the installation.

![CleanShot 2024-03-08 at 15 24 38](https://github.com/Azure-Samples/contoso-chat/assets/26237323/d3fd8867-7964-45cf-a0e0-217955c3fce0)

I am very close to run it.

Any idea how could it be fixed?

**Comment by DFMERA** [comment]
Did you try running connections/create-connections.ipynb? Also make sure your .env file has the correct keys and endpoints

**Comment by hisabimbola** [comment]
I had similar issue. What fixed for me was changing the api version param. The one used in the code does not work locally because it was not deployed

**Comment by mashhype** [comment]
> I had similar issue. What fixed for me was changing the api version param. The one used in the code does not work locally because it was not deployed

Same deal for me, except I needed to change the model that was deployed (the code has gpt-4, but I only have gpt-35-turbo)
