### ISSUE TITLE
What happened with ./provision.sh?

### ISSUE THREAD

**Issue by DFMERA** [Azure-Samples/contoso-chat#77]
Apparently the file ./provision.sh has been moved or replaced. How can I create azure resources now?

P.D. I was planning a pull request including a provision.ps1 so you don't need WSL to create azure resources. Would that make sense now?

**Comment by cassiebreviu** [comment]
Hey! We added the ability to run azd up but are still in the process of updating the instructions. Sorry for the confusion. You can grab the old provision.sh script from the source or use azd up to deploy the entire application and data.

**Comment by cassiebreviu** [comment]
Added script back until we update instructions. Thanks!
