### ISSUE TITLE
Deployment template validation failed: 'The provided value for the template parameter 'environmentName' is not valid. Length of the value should be greater than or equal to '1'

### ISSUE THREAD

**Issue by davew-msft** [Azure-Samples/contoso-chat#80]
fresh install running ./provision.sh

ERROR: {"code": "InvalidTemplate", "message": "Deployment template validation failed: 'The provided value for the template parameter 'environmentName' is not valid. Length of the value should be greater than or equal to '1'. Please see https://aka.ms/arm-syntax-parameters for usage details.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 14, "linePosition": 20, "path": "properties.template.parameters.environmentName.minLength"}}]}
ERROR: Failed to provision resources. Please check the error message above.

I also had to change provision.sh to overcome Issue 79:  https://github.com/Azure-Samples/contoso-chat/issues/79

**Comment by davew-msft** [comment]
I did this:  

param environmentName string = 'contchat' on Line 6 of main.bicep but I still see a bunch of new errors.  I'm going to stop filing bugs I guess and just fork this repo and try to fix everything then issue a PR I guess.

**Comment by cassiebreviu** [comment]
Please check the updated readme. If you wish to use codespaces and the provision.sh script (the way its documented in the instructions), then use the Stable commit ID below. If you wish to use azd up and the continuing upgrades, use main.

Stable : #cc2e808 | Version tested & used in Microsoft AI Tour (works on Skillable)
Active : main | Version under active development (breaking changes possible)

Thanks!

**Comment by nitya** [comment]
> [!NOTE]  
> This sample is currently undergoing a refresh in preparation for #MSBuild so many of these issues may no longer be relevant. We are closing issues now in preparation for the new version. Check back May 21, 2024 for updated release before posting new issues.
