### ISSUE TITLE
$RANDOM does not exist in `sh`

### ISSUE THREAD

**Issue by hisabimbola** [Azure-Samples/contoso-chat#82]
I tried setting up the project using `azd up` and I noticed that the endpointName var is not set correctly. This is because azd hooks only run in sh or pwsh and `$RANDOM` does not exist in `sh`.

Code reference
https://github.com/Azure-Samples/contoso-chat/blob/acfdf6d232b29ce865cce9932e1fb4ec57123dcd/infra/hooks/deployment.sh#L13

As a workaround, I've added my own `random_number` generator which does similar. 

```shell
random_number=$(od -An -N2 -i /dev/urandom | awk '{print $1}')
```

**Comment by nitya** [comment]
> [!NOTE]  
> This sample is currently undergoing a refresh in preparation for #MSBuild so many of these issues may no longer be relevant. We are closing issues now in preparation for the new version. Check back May 21, 2024 for updated release before posting new issues.
