### ISSUE TITLE
InvalidRunStatusError When Running "evaluate-chat-prompt-flow.ipynb" notebook

### ISSUE THREAD

**Issue by mashhype** [Azure-Samples/contoso-chat#88]
I get the following error: `InvalidRunStatusError: The input for batch run is incorrect. Input from key 'run.outputs' is an empty list, which means we cannot generate a single line input for the flow run. Please rectify the input and try again.`

when I run this cell `pf_azure_client.stream(eval_run_variant)`

Can anyone tell me what I am missing?

![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/d27c8c3c-c121-4725-ab1f-d1fecca7875e)

**Comment by nitya** [comment]
> [!NOTE]  
> This sample is currently undergoing a refresh in preparation for #MSBuild so many of these issues may no longer be relevant. We are closing issues now in preparation for the new version. Check back May 21, 2024 for updated release before posting new issues.
