### ISSUE TITLE
No module named 'promptflow.azure'

### ISSUE THREAD

**Issue by mashhype** [Azure-Samples/contoso-chat#92]
When running the "evaluate-chat-prompt-flow.ipynb" notebook in codespaces I get the following error..
Has something changed in this cell? I forked the latest version of the repo...
![image](https://github.com/Azure-Samples/contoso-chat/assets/4706698/85c0c7ab-4b3a-435b-97bb-2846ee68c57a)

**Comment by stevedenman** [comment]
I was getting the same. I've created a PR (#93) to include the promptflow-azure package, which appears to be used by a lot of the notebooks.

**Comment by youkhi** [comment]
I am having the same error. pip install promptflow.azure doesn't help as well.

**Comment by nitya** [comment]
> [!NOTE]  
> This sample is currently undergoing a refresh in preparation for #MSBuild so many of these issues may no longer be relevant. We are closing issues now in preparation for the new version. Check back May 21, 2024 for updated release before posting new issues.
