### ISSUE TITLE
404 when 'Run All' local PromptFlow

### ISSUE THREAD

**Issue by livlikwav** [Azure-Samples/contoso-chat#99]
I fiiled .env file with correct key and endpoint values in Azure Portal.  
But when I `run all` local PromptFlow, it fails at 'text embedding' step.  
I think that is OAI endpoint problem.

I'm in MS AI Tour Seoul 2024 now
Thank you, staffs

**Comment by nitya** [comment]
> [!NOTE]  
> This sample is currently undergoing a refresh in preparation for #MSBuild so many of these issues may no longer be relevant. We are closing issues now in preparation for the new version. Check back May 21, 2024 for updated release before posting new issues.
